services:
  backend:
    build:
      context: ./backendsample
      dockerfile: Dockerfile
    container_name: myfyp1-backendsample
    ports:
      - "5000:5000"
    volumes:
      - ./backendsample:/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontendsample
      dockerfile: Dockerfile
    container_name: myfyp1-frontendsample
    ports:
      - "3000:3000"
    volumes:
      - ./frontendsample:/app
    environment:
      - CHOKIDAR_USEPOLLING=true